# Number of days of inactivity before an issue becomes stale
daysUntilStale: 15
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 5
# Issues with these labels will never be considered stale
exemptLabels:
  - "not stale"
  - "good first issue ðŸ‘"
  - "good for beginners ðŸ˜ƒ"
  - "help wanted ðŸ†˜"
  - "Priority: High ðŸš¨"
  - "Showcase ðŸ’–"
  - "Topic: Reviews â­ï¸ðŸ’–"
  - "Status: Assigned âž¡"
  - "Status: Work in Progress ðŸ› "
  - "Type: Bug ðŸ›"
  - "Type: Documentation ðŸ“š"
  - "Type: Feature ðŸš€"
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Hi!

  This issue hasn't seen any activity recently. We close inactive issues after 20 days to manage the volume of issues we receive.

  If we missed this issue or you want to keep it open, please reply here. That will reset the timer and allow more time for this issue to be addressed before it is closed.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
unmarkComment: false
only: issues
