# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 5
# Issues with these labels will never be considered stale
exemptLabels: []
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Hi!

  This issue was labeled "awaiting response" or "needs reproduction" by a Chakra
  team member. In order to reduce the number of stale issues we have, I'm in
  charge of closing issues with no response or reproduction after 1 month.

  Since it's been 1 month and we still haven't received a response or
  reproduction, I will close this issue in 5 days. This issue will remain open
  if a response or reproduction is received before then.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
unmarkComment: false
only: issues
