import {
  BackgroundProps,
  BorderProps,
  ColorProps,
  FlexboxProps,
  GridProps,
  LayoutProps,
  ListProps,
  OtherProps,
  OutlineProps,
  PositionProps,
  ShadowProps,
  SpaceProps,
  TransformProps,
  TransitionProps,
  TypographyProps,
} from "./config"

export interface ChakraStyleProps
  extends SpaceProps,
    ColorProps,
    TransitionProps,
    TypographyProps,
    FlexboxProps,
    TransformProps,
    GridProps,
    LayoutProps,
    BorderProps,
    ShadowProps,
    BackgroundProps,
    ListProps,
    PositionProps,
    OutlineProps,
    OtherProps {}
