import { defineGlobalStyles } from "./def"

export const globalCss = defineGlobalStyles({
  "*": {
    fontFeatureSettings: '"cv11"',
    "--ring-inset": "var(--empty,/*!*/ /*!*/)",
    "--ring-offset-width": "0px",
    "--ring-offset-color": "#fff",
    "--ring-color": "rgba(66, 153, 225, 0.6)",
    "--ring-offset-shadow": "0 0 #0000",
    "--ring-shadow": "0 0 #0000",
    "--brightness": "var(--empty,/*!*/ /*!*/)",
    "--contrast": "var(--empty,/*!*/ /*!*/)",
    "--grayscale": "var(--empty,/*!*/ /*!*/)",
    "--hue-rotate": "var(--empty,/*!*/ /*!*/)",
    "--invert": "var(--empty,/*!*/ /*!*/)",
    "--saturate": "var(--empty,/*!*/ /*!*/)",
    "--sepia": "var(--empty,/*!*/ /*!*/)",
    "--drop-shadow": "var(--empty,/*!*/ /*!*/)",
    "--backdrop-blur": "var(--empty,/*!*/ /*!*/)",
    "--backdrop-brightness": "var(--empty,/*!*/ /*!*/)",
    "--backdrop-contrast": "var(--empty,/*!*/ /*!*/)",
    "--backdrop-grayscale": "var(--empty,/*!*/ /*!*/)",
    "--backdrop-hue-rotate": "var(--empty,/*!*/ /*!*/)",
    "--backdrop-invert": "var(--empty,/*!*/ /*!*/)",
    "--backdrop-opacity": "var(--empty,/*!*/ /*!*/)",
    "--backdrop-saturate": "var(--empty,/*!*/ /*!*/)",
    "--backdrop-sepia": "var(--empty,/*!*/ /*!*/)",
    "--global-font-mono": "fonts.mono",
    "--global-font-body": "fonts.body",
    "--global-color-border": "colors.border",
  },
  html: {
    color: "fg",
    bg: "bg",
    lineHeight: "1.5",
    colorPalette: "gray",
  },
  "*::placeholder": {
    color: "fg.muted/80",
  },
  "*::selection": {
    bg: "colorPalette.muted/80",
  },
})
