export { default } from "./Icons"
export * from "./Icons"
export * from "./CopyIcon"
export * from "./SearchIcon"
export * from "./Search2Icon"
export * from "./MoonIcon"
export * from "./SunIcon"
export * from "./AddIcon"
export * from "./SmallAddIcon"
export * from "./SettingsIcon"
