export { Highlight } from "./highlight"
export type { HighlightProps } from "./highlight"
export { Mark } from "./mark"
export type { MarkProps } from "./mark"
export { useHighlight } from "./use-highlight"
export type { UseHighlightProps } from "./use-highlight"
