import { datePickerAnatomy } from "../../anatomy"
import { defineSlotRecipe } from "../../styled-system"

export const datePickerSlotRecipe = defineSlotRecipe({
  className: "date-picker",
  slots: datePickerAnatomy.keys(),
  base: {
    root: {
      display: "flex",
      flexDirection: "column",
      gap: "1.5",
      width: "full",
      maxWidth: "24rem",
    },
    label: {
      textStyle: "sm",
      fontWeight: "medium",
      color: "fg",
      userSelect: "none",
    },
    control: {
      display: "flex",
      alignItems: "center",
      gap: "2",
      width: "full",
    },
    input: {
      flex: "1",
      minWidth: "0",
      height: "10",
      px: "3",
      textStyle: "sm",
      background: "transparent",
      borderWidth: "1px",
      borderColor: "border",
      borderRadius: "l2",
      color: "fg",
      outline: "none",
      transitionDuration: "normal",
      transitionProperty: "border-color, box-shadow",
      _placeholder: {
        color: "fg.muted",
      },
      _focus: {
        borderColor: "colorPalette.solid",
        boxShadow: "0 0 0 1px var(--colors-color-palette-solid)",
      },
      _invalid: {
        borderColor: "fg.error",
        _focus: {
          borderColor: "fg.error",
          boxShadow: "0 0 0 1px var(--colors-fg-error)",
        },
      },
      _disabled: {
        opacity: 0.5,
        filter: "grayscale(100%)",
      },
    },
    trigger: {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      width: "10",
      height: "10",
      flexShrink: 0,
      background: "transparent",
      borderWidth: "1px",
      borderColor: "border",
      borderRadius: "l2",
      color: "fg",
      outline: "none",
      transitionDuration: "normal",
      transitionProperty: "background, border-color",
      cursor: "pointer",
      _hover: {
        background: "bg.subtle",
      },
      _focusVisible: {
        borderColor: "colorPalette.solid",
        boxShadow: "0 0 0 1px var(--colors-color-palette-solid)",
      },
      _disabled: {
        opacity: 0.5,
        filter: "grayscale(100%)",
        pointerEvents: "none",
      },
      _icon: {
        width: "4",
        height: "4",
      },
    },
    content: {
      display: "flex",
      flexDirection: "column",
      gap: "3",
      p: "4",
      minWidth: "17.5rem",
      background: "bg.panel",
      borderWidth: "1px",
      borderColor: "border",
      borderRadius: "l3",
      boxShadow: "md",
      zIndex: "dropdown",
      outline: "none",
      _open: {
        animation: "fade-in",
      },
      _closed: {
        animation: "fade-out",
      },
    },
    view: {
      display: "flex",
      flexDirection: "column",
      gap: "3",
      _hidden: {
        display: "none",
      },
    },
    viewControl: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: "2",
    },
    viewTrigger: {
      display: "inline-flex",
      flex: "1",
      alignItems: "center",
      justifyContent: "center",
      gap: "1",
      py: "1.5",
      px: "2",
      textStyle: "sm",
      fontWeight: "semibold",
      background: "transparent",
      borderRadius: "l1",
      color: "fg",
      transition: "background 0.15s ease",
      _hover: {
        background: "bg.subtle",
      },
      _focusVisible: {
        background: "bg.subtle",
        outline: "2px solid var(--colors-color-palette-focus-ring)",
      },
    },
    prevTrigger: {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      width: "8",
      height: "8",
      borderRadius: "l2",
      color: "fg",
      transitionDuration: "normal",
      transitionProperty: "background, border-color",
      _hover: {
        background: "bg.subtle",
      },
      _focusVisible: {
        background: "bg.subtle",
        boxShadow: "0 0 0 2px var(--colors-color-palette-focus-ring)",
      },
      _disabled: {
        opacity: 0.4,
        cursor: "not-allowed",
      },
      _icon: {
        width: "4",
        height: "4",
      },
    },
    nextTrigger: {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      width: "8",
      height: "8",
      borderRadius: "l2",
      color: "fg",
      transitionDuration: "normal",
      transitionProperty: "background, border-color",
      _hover: {
        background: "bg.subtle",
      },
      _focusVisible: {
        background: "bg.subtle",
        boxShadow: "0 0 0 2px var(--colors-color-palette-focus-ring)",
      },
      _disabled: {
        opacity: 0.4,
        cursor: "not-allowed",
      },
      _icon: {
        width: "4",
        height: "4",
      },
    },
    rangeText: {
      textStyle: "sm",
      fontWeight: "semibold",
      color: "fg",
    },
    table: {
      width: "full",
      borderCollapse: "separate",
      borderSpacing: "0",
    },
    tableHeader: {
      py: "2",
      textStyle: "xs",
      fontWeight: "medium",
      color: "fg.muted",
      textAlign: "center",
      textTransform: "uppercase",
      letterSpacing: "wider",
    },
    tableCell: {
      p: "0",
      textAlign: "center",
    },
    tableCellTrigger: {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      width: "full",
      height: "9", // 2.25rem
      textStyle: "sm", // 0.8125rem -> close to sm
      fontWeight: "regular",
      background: "transparent",
      borderRadius: "l2",
      color: "fg",
      userSelect: "none",
      _hover: {
        background: "bg.subtle",
      },
      _focusVisible: {
        outline: "2px solid var(--colors-color-palette-solid)",
        outlineOffset: "-2px",
        zIndex: "1",
      },
      _today: {
        fontWeight: "semibold",
        color: "colorPalette.fg",
      },
      _selected: {
        background: "colorPalette.solid",
        color: "colorPalette.contrast",
        fontWeight: "medium",
        _hover: {
          background: "colorPalette.solid",
        },
      },
      // Range Selection Logic
      "&[data-in-range]": {
        background: "colorPalette.subtle",
        color: "colorPalette.fg",
        borderRadius: "0",
        _hover: { background: "colorPalette.subtle" },
      },
      "&[data-range-start]": {
        background: "colorPalette.solid",
        color: "colorPalette.contrast",
        borderRadius: "0",
        borderStartRadius: "l2",
        _hover: { background: "colorPalette.solid" },
      },
      "&[data-range-end]": {
        background: "colorPalette.solid",
        color: "colorPalette.contrast",
        borderRadius: "0",
        borderEndRadius: "l2",
        _hover: { background: "colorPalette.solid" },
      },
      "&[data-range-start][data-range-end]": {
        borderRadius: "l2",
      },
      _disabled: {
        color: "fg.muted",
        opacity: 0.4,
        cursor: "not-allowed",
        _hover: { background: "transparent" },
      },
    },
    // Styles for Month/Year grid views
    monthSelect: {
      height: "8",
      px: "2",
      textStyle: "sm",
      background: "bg.subtle",
      borderWidth: "1px",
      borderColor: "border",
      borderRadius: "l1",
      outline: "none",
      _focusVisible: {
        borderColor: "colorPalette.solid",
        boxShadow: "0 0 0 1px var(--colors-color-palette-solid)",
      },
    },
    yearSelect: {
      height: "8",
      px: "2",
      textStyle: "sm",
      background: "bg.subtle",
      borderWidth: "1px",
      borderColor: "border",
      borderRadius: "l1",
      outline: "none",
      _focusVisible: {
        borderColor: "colorPalette.solid",
        boxShadow: "0 0 0 1px var(--colors-color-palette-solid)",
      },
    },
    presetTrigger: {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      py: "1.5",
      px: "3",
      textStyle: "xs",
      fontWeight: "medium",
      background: "bg.subtle",
      borderWidth: "1px",
      borderColor: "border",
      borderRadius: "l2",
      color: "fg",
      transitionDuration: "normal",
      transitionProperty: "background, border-color",
      _hover: {
        background: "bg.muted",
      },
      _focusVisible: {
        borderColor: "colorPalette.solid",
        boxShadow: "0 0 0 1px var(--colors-color-palette-solid)",
      },
    },
    clearTrigger: {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      p: "2",
      textStyle: "xs",
      fontWeight: "medium",
      background: "transparent",
      borderWidth: "1px",
      borderColor: "border",
      borderRadius: "l2",
      color: "fg.muted",
      cursor: "pointer",
      _hover: {
        background: "bg.subtle",
        color: "fg",
      },
      _focusVisible: {
        borderColor: "colorPalette.solid",
        boxShadow: "0 0 0 1px var(--colors-color-palette-solid)",
      },
    },
  },
  variants: {
    size: {
      sm: {
        input: { h: "9", px: "2.5", textStyle: "sm" },
        trigger: { h: "9", w: "9" },
      },
      md: {
        input: { h: "10", px: "3", textStyle: "sm" },
        trigger: { h: "10", w: "10" },
      },
      lg: {
        input: { h: "11", px: "3.5", textStyle: "md" },
        trigger: { h: "11", w: "11" },
      },
    },
  },
  defaultVariants: {
    size: "md",
  },
})
