// Dear maintainers, please arrange components alphabetically. Thanks :)

const componentRegister = [
  "Alert",
  "AlertDialog",
  "Avatar",
  "AvatarGroup",
  "Badge",
  "Box",
  "Breadcrumb",
  "Button",
  "Checkbox",
  "CircularProgress",
  "CloseButton",
  "Code",
  "Collapse",
  "ControlBox",
  "Drawer",
  "FormControl",
  "Heading",
  "Icon",
  "IconButton",
  "Input",
  "InputAddon",
  "InputGroup",
  "Link",
  "Menu",
  "NumberInput",
  "Popover",
  "Progress",
  "PseudoBox",
  "Radio",
  "Slider",
  "Spinner",
  "Stat",
  "Tabs",
  "Tag",
  "Textarea",
  "Toast",
  "Tooltip",
];
export default componentRegister;
