name: Post to Discord

on:
  pull_request:
    types: [closed]
    branches:
      - docs/changelog-updates

jobs:
  merge_job:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Yarn cache path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: main

      - name: Enable node
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Load Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile && yarn bootstrap

      - name: Post updates to Discord announcement channel
        run: yarn discord
